stages:
  - pages
  - build
  - k8s-secret-create
  - deploy

pages:
  stage: pages
  image: node:16-alpine

  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public

include:
  - project: "templates/kaniko-build"
    file: ".gitlab-ci-kaniko-build.yml"
  - project: "templates/argocd-deploy"
    file: ".gitlab-ci-argocd-deploy.yml"

