stages:
  - build
  - k8s-secret-create
  - deploy

include:
  - project: "templates/kaniko-build"
    file: ".gitlab-ci-kaniko-build.yml"
  - project: "templates/argocd-deploy"
    file: ".gitlab-ci-argocd-deploy.yml"

